print("\nNow let's add two value that you enter!\nEnter two integers:")
a = input()
b = input()
num1 = int(a)
num2 = int(b)
print("The sum of the values you entered is " + str(num1+num2) + ".")
print("What about finding the difference? \nEnter two more integers:")
num3 = int(input())
num4 = int(input())
print("The difference is " + str(num3-num4) + ".")
print("There is something called 'eval()'. Let's checkout what that is!")
print("You gotta enter two more values. Floats are best here!")
num5 = eval(input())
num6 = eval(input())
print("Wow! 'eval()' is working perfectly!\nAgain, the sum of the values you entered is " + str(num5+num6))
